# Generated by Django 5.1.15 on 2026-09-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="mode",
            field=models.CharField(
                choices=[("llm", "llm")], default="llm", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="target",
            field=models.CharField(
                help_text="Repo URL, live URL/host, or a local dir.", max_length=500
            ),
        ),
    ]
